### ISSUE TITLE
Support `@import` align

### ISSUE THREAD

**Issue by samzeng** [adrianlee44/atom-aligner-stylus#1]
Case like this:

```stylus
@import 'aaaa' // a
@import 'b' // b
@import 'ccccc' // c
```

**Comment by adrianlee44** [comment]
Are you trying to align the comments?

**Comment by samzeng** [comment]
Yes

**Comment by adrianlee44** [comment]
Which stylus language package are you using?

If you are using https://atom.io/packages/stylus. It seems like it's not tokenizing trailing comments.

**Comment by samzeng** [comment]
Yes, I use https://atom.io/packages/stylus package.

    It seems like it's not tokenizing trailing comments.

You mean this? https://github.com/matthojo/language-stylus/blob/master/grammars/stylus.cson#L77

**Comment by adrianlee44** [comment]
That line seems to be for comment only line that may or may not have leading tabs.
