### ISSUE TITLE
not working if use colon

### ISSUE THREAD

**Issue by nska02** [adrianlee44/atom-aligner-stylus#2]
Hi,

First, thanks for the package and awesome work!
Second, just fyi, not a deal breaker but when using colons, alignment doesn't work (it used to, at least on my platform > Mac).

This won't align:
```
.some-div
  color: blue
  background-color: red
```

But this will:
```
.some-div
  color            blue
  background-color red
```

As stylus is all about flexibility in the markup, I thought this needed to be raised.
Cheers

**Comment by adrianlee44** [comment]
Thanks for reporting this. Aligner pre-1.0 used to have a default config for `:` which was original designed for JavaScript/CoffeeScript only. The config has since been removed in favor for language specific configuration. Let me update this package to support `:`
